blog/app.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

from blog.user.views import user
from blog.report.views import report


db = SQLAlchemy()

def create_app() -> Flask:
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_pyfile('config.py')
    print("DEBUG:", app.config.get("DEBUG"))
    print("DATABASE_URI:", app.config.get("SQLALCHEMY_DATABASE_URI"))
    print("Secret Key:", app.config.get("SECRET_KEY"))
    db.init_app(app)

    register_blueprints(app)
    return app


def register_blueprints(app: Flask) -> None:
    app.register_blueprint(user)
    app.register_blueprint(report)




blog/report/views.py
from flask import Blueprint, render_template

report = Blueprint(
    'report',
    __name__,
    url_prefix='/reports',
    static_folder='../static',
    template_folder='../templates',
)


@report.route('/')
def report_list():
    return render_template('report/list.html', reports=[1, 2, 3, 4, 5])


blog/user/views.py
from flask import Blueprint, render_template, redirect
from werkzeug.exceptions import NotFound

user = Blueprint(
    'user',
    __name__,
    url_prefix='/users',
    static_folder='../static',
    template_folder='../templates'
    )

USERS = {
    1: 'Alice',
    2: 'John',
    3: 'Bob',
    4: 'Dave',
    5: 'Eve',
    6: 'Mike',
}


@user.route('/')
def user_list():
    return render_template('users/list.html', users=USERS)


@user.route('/<int:pk>')
def get_user(pk: int):
    try:
        user_name = USERS[pk]
    except KeyError:
        # raise NotFound(f'User_id {pk} does not exist')
        return redirect('/users/')
    return render_template('users/details.html', user_name=user_name)

blog/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}My app - {% endblock %}
    </title>
    {% block css %} {% endblock %}
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet" >
  </head>
  <body>
    {% include 'navbar.html' %}
    <div class="container">
        {% block body %}{% endblock %}
    </div>


    {% block js %}{% endblock %}

    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}" ></script>
  </body>
</html>





blog/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
{#        <a class="navbar-brand" href="#">Navbar</a>#}
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" href="{{ url_for('user.user_list') }}">Users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('report.report_list') }}">Reports</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

blog/templates/report/list.html
{% extends 'base.html' %}

{% block title %}
    Reports list
{% endblock %}

{% block body %}

    <div class="row">
        <div class="col">
            <h1>Reports: </h1>
            {% for report in reports %}
                <ul>
                    <li>{{ report }}</li>
                </ul>
            {% endfor %}
        </div>
    </div>




{% endblock %}


blog/templates/users/details.html
{% extends 'base.html' %}

{% block title %}
    Users detail
{% endblock %}

{% block body %}
    <h1> {{ user_name }} </h1>
    <button type="button" class="btn btn-danger">Danger</button>

{% endblock %}


blog/templates/users/list.html
{% extends 'base.html' %}

{% block title %}
    Users list
{% endblock %}

{% block body %}

    <div class="row">
        <div class="col">
            <h1>Users: </h1>
            {% for user_id in users %}
                <ul>
                    <li><a href="{{ url_for('user.get_user', pk=user_id) }}">{{ users[user_id] }}</a></li>
                </ul>
            {% endfor %}
        </div>
    </div>




{% endblock %}
